spring:
  cloud:
    gateway:
      # 配置跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      # 路由转发
      routes:
      - id: member
        uri: http://127.0.0.1:8080
        predicates:
        - Path=/member/**

server:
  port: 8000

